// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-variants/Cards.tsx": () => import("../components/mockups/dashboard-variants/Cards.tsx"),
  "./components/mockups/dashboard-variants/Cockpit.tsx": () => import("../components/mockups/dashboard-variants/Cockpit.tsx"),
  "./components/mockups/dashboard-variants/Glass.tsx": () => import("../components/mockups/dashboard-variants/Glass.tsx"),
  "./components/mockups/dashboard-variants/RingBlue.tsx": () => import("../components/mockups/dashboard-variants/RingBlue.tsx"),
  "./components/mockups/dashboard-variants/RingOrange.tsx": () => import("../components/mockups/dashboard-variants/RingOrange.tsx"),
  "./components/mockups/dashboard-variants/RingPurple.tsx": () => import("../components/mockups/dashboard-variants/RingPurple.tsx"),
  "./components/mockups/dashboard-variants/VariantA.tsx": () => import("../components/mockups/dashboard-variants/VariantA.tsx"),
  "./components/mockups/dashboard-variants/VariantB.tsx": () => import("../components/mockups/dashboard-variants/VariantB.tsx"),
  "./components/mockups/dashboard-variants/VariantC.tsx": () => import("../components/mockups/dashboard-variants/VariantC.tsx"),
  "./components/mockups/dashboard-variants/VariantD.tsx": () => import("../components/mockups/dashboard-variants/VariantD.tsx"),
  "./components/mockups/themes/ThemeBlue.tsx": () => import("../components/mockups/themes/ThemeBlue.tsx"),
  "./components/mockups/themes/ThemeLight.tsx": () => import("../components/mockups/themes/ThemeLight.tsx"),
  "./components/mockups/themes/ThemeOrange.tsx": () => import("../components/mockups/themes/ThemeOrange.tsx"),
  "./components/mockups/themes/ThemePurple.tsx": () => import("../components/mockups/themes/ThemePurple.tsx")
};
