// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-variants/Cards.tsx": () => import("../components/mockups/dashboard-variants/Cards.tsx"),
  "./components/mockups/dashboard-variants/Cockpit.tsx": () => import("../components/mockups/dashboard-variants/Cockpit.tsx"),
  "./components/mockups/dashboard-variants/Glass.tsx": () => import("../components/mockups/dashboard-variants/Glass.tsx")
};
